### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by BlooketHackerx** [gBasil/WinDemonica#1]
I know this is off-topic, but I cannot contact you any other way so here I am. 
This is not related to your "WinDemonica", so if you don't read it I don't blame you.

I just wanted to know if there is a way to "bypass" the extension called Goguardian. 
I tried every method I could think of but my school is smart. They blocked Chrome OS SETTINGS, inspect element, dev tools in extension manager so I can't get rid of it nor can I install an extension to block it. I cannot factory reset my chromebook, as they monitor everyone closely and if they lose contact with my chromebook I am positive they will find out. I tried proxies, didn't work. I can't get a vpn, nor can I access the google play store. I tried even finding a way to use CROSH to uninstall or block it but still failed. 
I wish to simply block it from working though, as when I am at school I need it on again so there will not be any suspicions. 
I can barely do anything and they also blocked a lot of the shortcuts. I also cannot sign in with another account (My own personal email) because when the chromebook starts, it takes me to a screen that I have to use my email for and can't use anything else. Please let me know if you know of any way to get past this, kind regards -Someone

**Comment by BlooketHackerx** [comment]
@gBasil

**Comment by gBasil** [comment]
GitHub is not a messageboard. I have ample ways of contacting me on my website.
